mysite/blog/urls.py
from django.conf.urls import url
from blog.views import *

urlpatterns =[
    # Example: /
    url(r'^$', PostLV.as_view(), name='index'),

    # Example: post/ (same as /)
    url(r'^post/$', PostLV.as_view(), name='post_list'),

    # Example: post/django-example
    # blog/post/(?P<slug>[-w]+)/$
    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),

    # Example: archive/
    url(r'^archive/$', PostAV.as_view(), name='post_archive'),

    # Example: /2017/
    url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),

    # Example: /2017/may
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name='post_month_archive'),

    # Example: /2017/may/27
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),

    # Example: /today/
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),

    # Example: /tag/
    url(r'^tag/$', TagTV.as_view(), name='tag_cloud'),

    # Example: /tag/tagname/
    url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),

    # Example: /search/
    url(r'^search/$', SearchFormView.as_view(), name='search'),
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from mysite.views import HomeView
from mysite.views import UserCreateView, UserCreateDoneTV


urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^photo/', include('photo.urls', namespace='photo')),

    # 인증 URL
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

    # Class-base views for Bookmark app
    # url(r'^bookmark/$', BookmarkLV.as_view(), name='index'),
    # url(r'^bookmark/(?P<pk>\d+)/$', BookmarkDV.as_view(), name='detail'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )

mysite/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <title>{% block title %}Django web Programming {% endblock %}</title>

    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}"/>
</head>

<body>
<div id="header">
    <h2 class="maintitle">Easy &amp; Fast Django Web Programming </h2>
    <h4 class="welcome">Welcome, <a href="#"> ASVV </a> /
        <a href="#"> Change Password</a> /
        <a href="#"> Logout </a>
    </h4>
</div>

<div id="menu">
    <li><a href="{% url 'home' %}"> HOME</a></li>
    <li><a href="{% url 'bookmark:index' %}"> Bookmark</a></li>
    <li><a href="{% url 'blog:index' %}"> Blog</a></li>
    <li><a href="{% url 'photo:index' %}"> Photo</a></li>

    <li>
        <a href="#"> Add&bigtriangledown;</a>
        <ul>
            <li><a href="#"> BOOKMARK </a></li>
            <li><a href="#"> BLOG </a></li>
            <li><a href="#"> PHOTO </a></li>
        </ul>
    </li>
    <li>
        <a href="#">Change&bigtriangledown;</a>
        <ul>
            <li><a href="#">BOOKMARK</a></li>
            <li><a href="#">BLOG</a></li>
            <li><a href="#">PHOTO</a></li>
        </ul>
    </li>

    <li><a href="{% url 'blog:post_archive' %}">Archive</a></li>
    <li><a href="{% url 'blog:search' %}">Search</a></li>
    <li><a href="{% url 'admin:index' %}">Admin</a></li>
</div>

{% block content %}{% endblock %}
{% block footer %} {% endblock %}

</body>
</html>

mysite/templates/home.html
{% extends "base.html" %}

{% block title %}home.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/home.css" %}{% endblock %}

{% block content %}

<div id="content_home">

    <div id="homeimg">
        <a href="/"><img src="{% static 'img/django-actor-big.jpg' %}" style="height:256px;"/></a>
        <h4 style="margin: 0;">This is Django powered web site.</h4>
    </div>

    <hr style="margin: 5px 0;">

    <h2>Select Application</h2>

    <table id="applist">
        <tr>
        <td><b><i><a href="{% url 'bookmark:index' %}">Bookmark</a></i><b></td>
        <td>You can write your own post and share to others. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo</td>
        <td id="Edit"><i><a href="#">Add</a></i></td>
        <td id="Edit"><i><a href="#">Change</a></i></td>
        </tr>

        <tr>
        <td><b><i><a href="{% url 'blog:index' %}">Blog</a></i><b></td>
        <td>You can write your own post and share to others. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo</td>
        <td id="Edit"><i><a href="#">Add</a></i></td>
        <td id="Edit"><i><a href="#">Change</a></i></td>
        </tr>

        <tr>
        <td><b><i><a href="#">Photo</a></i><b></td>
        <td>You can write your own post and share to others. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo</td>
        <td id="Edit"><i><a href="#">Add</a></i></td>
        <td id="Edit"><i><a href="#">Change</a></i></td>
        </tr>
    </table>
</div>
{% endblock content %}

{% block footer %}
<div id="footer">
    &copy; shkim 2016
</div>
{% endblock footer %}